### ISSUE TITLE
set the format of text in new version

### ISSUE THREAD

**Issue by HaoHao-Ting** [RezMike/2048#2]
in your code and [KorGE Tutorial](https://blog.korge.org/korge-tutorial-writing-2048-game-step-1/)
``` kotlin
text("0", cellSize * 0.5, Colors.WHITE, font) {
	setTextBounds(Rectangle(0.0, 0.0, bgBest.width, cellSize - 24.0))
        format = format.copy(align = Html.Alignment.MIDDLE_CENTER) //  The ide shows: Unresolved reference.
        // I change the code to 
       // setFormat(align = TextAlignment.MIDDLE_CENTER)
       // It no longer reports an error, but the text has disappeared
	alignTopToTopOf(bgBest, 12.0)
	centerXOn(bgBest)
}
```

My environment is :
Android studio :4.1.1
Korge gradle pluge 1.12.2.2

So could your mind tell me how to fix the code. thanks a lot.

**Comment by RezMike** [comment]
@HaoHao-Ting try to change that line to this one:
```
alignment = TextAlignment.MIDDLE_CENTER
```

**Comment by RezMike** [comment]
@HaoHao-Ting I just updated the project to use KorGE gradle plugin 2.0.0.1. You can look here to see the changes https://github.com/RezMike/2048/commit/bf7566000071888fe2fcfacb531f58d1cdb2643f

**Comment by HaoHao-Ting** [comment]
Thanks a lot. It works.
