### ISSUE TITLE
Why the text.centerOn() is notwoking?

### ISSUE THREAD

**Issue by ijero** [RezMike/2048#3]
```kotlin
    val font = resourcesVfs["fonts/clear_sans.fnt"].readBitmapFont()
    text("2048", cellSize * 0.5, Colors.WHITE, font).centerOn(bgLogo)
```

runJvm：
![image](https://user-images.githubusercontent.com/7928858/103437938-38e87400-4c68-11eb-8b05-77cedc58ac72.png)

**Comment by RezMike** [comment]
@ijero it's because of the new implementation of `text` element in KorGE 2.0. Try to use `oldText` instead, this should work as expected. I don't change the code because I'm waiting for a fix for this in KorGE.

**Comment by ijero** [comment]
Thanks, I used textOld View, it shows the centering property correctly.

```kotlin
 textOld("2048", cellSize * 0.5, Colors.WHITE, font).centerOn(bgLogo)
```
