### ISSUE TITLE
Please update source to use version korgePluginVersion=2.3.2

### ISSUE THREAD

**Issue by tcnesham** [RezMike/2048#5]
There are some breaking changes to this game source with korgePluginVersion=2.3.2. Can this repo be updated to the newer korgePluginVersion?

**Comment by RezMike** [comment]
Yes, but I don't have free time for the next week or two to do it

**Comment by tcnesham** [comment]
Thanks. I got it working using korge-gradle-plugin:2.3.2. Not much changed for this game. However, the code for Container.showGameOver still has a couple minor breaking changes that I haven't figured out what is needed. 
In main, line 157 can change to:
```
keys {
        down {
            when (it.key) {
                Key.LEFT -> moveBlocksTo(Direction.LEFT)
                Key.RIGHT -> moveBlocksTo(Direction.RIGHT)
                Key.UP -> moveBlocksTo(Direction.TOP)
                Key.DOWN -> moveBlocksTo(Direction.BOTTOM)
                else -> Unit
            }
        }
    }
```

**Comment by RezMike** [comment]
@tcnesham I updated korge gradle version to 2.4.1 in the project and fixed incompatibilities (skins were removed in korge, new correct implementation is in the last commit)

**Comment by tcnesham** [comment]
Thanks, works great!
